# Generated by Django 4.2.6 on 2023-11-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_prodcutdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodcutdb',
            name='PROPRICE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
