# Generated by Django 4.2.6 on 2023-12-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_alter_prodcutdb_proprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField(blank=True, null=True)),
                ('TITLE', models.CharField(blank=True, max_length=100, null=True)),
                ('DESC', models.CharField(blank=True, max_length=100, null=True)),
                ('IMAGE', models.ImageField(blank=True, null=True, upload_to='Images')),
            ],
        ),
    ]
