# Generated by Django 4.2.6 on 2023-12-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_blogdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdb',
            name='DESC',
        ),
        migrations.AddField(
            model_name='blogdb',
            name='FULLDESC',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='blogdb',
            name='SHORTDESC',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
