# Generated by Django 4.2.6 on 2023-12-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_remove_blogdb_desc_blogdb_fulldesc_blogdb_shortdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodcutdb',
            name='PROPRICE',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
